# Generated by Django 6.0.3 on 2026-04-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_studentprofile_avatar_alter_studentprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
