# Generated by Django 6.0.3 on 2026-04-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_studentprofile_course_studentprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='course_thumbs/')),
                ('duration', models.CharField(max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
