# Generated by Django 6.0.3 on 2026-04-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_studentprofile_is_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='courses',
            name='icon_class',
            field=models.CharField(default='fa-solid fa-graduation-cap', max_length=100),
        ),
    ]
